### PR TITLE
fix: add editor-style entrypoint

### LINKED ISSUE #174: Editor Stylesheet does not need to be loaded outside of SCRIPT_DEBUG mode
### Describe the bug

I was tracking down a console error seen on a Newspack site using Publisher Media Kit.

```
tinymce.min.js:2 
       GET https://domain.com/wp-content/plugins/publisher-media-kit/dist/css/editor-style.min.css?wp-mce-49110-20201110 net::ERR_ABORTED 404 (Not Found)
```

This file does not appear to be built. It is not listed in the entrypoints: https://github.com/10up/publisher-media-kit/blob/develop/package.json#L60-L69

Should editor style be added as its own entrypoint to support this code? https://github.com/10up/publisher-media-kit/blob/develop/includes/core.php#L338-L353

### Steps to Reproduce

Load New Post page with plugin enabled. Do not have SCRIPT_DEBUG enabled. Observe the 404.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by davisshaver**
### Description of the Change

Checkout branch and build

Load New Post page with plugin enabled. Do not have SCRIPT_DEBUG enabled. Do not observe the 404.

Closes https://github.com/10up/publisher-media-kit/issues/174

### Changelog Entry

Fixed: Build editor-style entrypoint

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by davisshaver** [comment]
I could use some help with reviewing and verifying this fix. After looking at it more closely, it kind of seems like this was never working for either dev/debug or prod modes. So I wonder if we even need this stylesheet loaded?

File: includes/core.php [hunk 1]
```diff
@@ -348,8 +348,8 @@ function mce_css( $stylesheets ) {
 	}
 
 	return $stylesheets . PUBLISHER_MEDIA_KIT_URL . ( ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ?
-			'assets/css/frontend/editor-style.css' :
-			'dist/css/editor-style.min.css' );
+			'assets/css/admin/editor-style.css' :
```
Comment (dkotter) [inline includes/core.php]: So I was curious on the history here of why we were referencing a file that doesn't exist. What I found is that this function (`mce_css`) was added in the initial scaffolding of this plugin and at that point, there was a `assets/css/frontend/editor-style.css` file. Shortly after that, this file was deleted but the code here was not.

My opinion here is we should just delete this `mce_css` function all together. It has never done anything for us so I don't think there's any loss by removing it.

Alternatively, if we want to keep this around (it is supposed to load CSS for the TinyMCE editor, not sure how much we even support that in this particular plugin), I think instead of building a new CSS file (`assets/css/admin/editor-style.css` here), we can use the existing `admin-style.css` file, as that contains the code found in `editor-style.css`

**Review by dkotter — CHANGES_REQUESTED** [review]

File: includes/core.php (hunk 1 above)
Comment (davisshaver) [reply includes/core.php]: Thanks for reviewing @dkotter. Your explanation makes a lot of sense to me. I haven't noticed any functional issues with not having the stylesheet. I think removing the function altogether makes sense. If you agree I can update the PR accordingly.

Comment (dkotter) [reply includes/core.php]: Yeah, I would just remove it at this point. If we need/want to try styling the Classic Editor view, this is something we can bring back but since it hasn't ever actually been working, think it's easiest to just remove for now

Comment (davisshaver) [reply includes/core.php]: @dkotter Updated the PR

**Review by dkotter — APPROVED** [review]
