### PR TITLE
Fix/154 PHP Version Check

### LINKED ISSUE #154: Add PHP checks
More info: https://github.com/10up/convert-to-blocks/pull/123#issuecomment-1611475826

### PR DESCRIPTION
**Pull request by bmarshall511**
### Description of the Change

Added a minimum PHP version check for 7.4.

Closes #154 

### How to test the Change

1. Spin up the site with a version of PHP below 7.4
2. Verify an admin notice has been added alerting the user of the failed check

### Changelog Entry

> Added - >=PHP 7.4 version check

### Credits

Props @bmarshall511 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: publisher-media-kit.php [hunk 1]
```diff
@@ -24,6 +24,49 @@
...
+	return '7.4';
+}
+
+/**
+ * Checks whether PHP installation meets the minimum requirements
+ *
+ * @return bool True if meets minimum requirements, false otherwise.
+ */
+function pmk_site_meets_php_requirements() {
+
```
Comment (faisal-alvi) [inline publisher-media-kit.php]:
```suggestion
```

File: publisher-media-kit.php [hunk 2]
```diff
@@ -24,6 +24,49 @@
...
+							esc_html( pmk_minimum_php_requirement() )
+						)
+					);
+					?>
+				</p>
+			</div>
+			<?php
+		}
+	);
+	return;
```
Comment (faisal-alvi) [inline publisher-media-kit.php:68]:
```suggestion

	return;
```

File: publisher-media-kit.php [hunk 3]
```diff
@@ -24,6 +24,49 @@
 define( 'PUBLISHER_MEDIA_KIT_INC', PUBLISHER_MEDIA_KIT_PATH . 'includes/' );
 define( 'PUBLISHER_MEDIA_KIT_BLOCK_PATTERS', PUBLISHER_MEDIA_KIT_PATH . 'includes/block-patterns/' );
 
+/**
+ * Get the minimum version of PHP required by this plugin.
+ *
+ * @return string Minimum version required.
+ */
+function pmk_minimum_php_requirement() {
```
Comment (faisal-alvi) [inline publisher-media-kit.php]: I think we should use namespace instead of a prefix as we are using it in rest of the plugin files?

File: publisher-media-kit.php [hunk 4]
```diff
@@ -24,6 +24,49 @@
...
+	return '7.4';
+}
+
+/**
+ * Checks whether PHP installation meets the minimum requirements
```
Comment (faisal-alvi) [inline publisher-media-kit.php]:
```suggestion
 * Checks whether PHP installation meets the minimum requirements.
```

File: publisher-media-kit.php [hunk 5]
```diff
@@ -24,6 +24,49 @@
...
+ *
+ * @return bool True if meets minimum requirements, false otherwise.
```
Comment (faisal-alvi) [inline publisher-media-kit.php]:
```suggestion
 * @return bool true if meets minimum requirements, false otherwise.
```

File: publisher-media-kit.php [hunk 6]
```diff
@@ -24,6 +24,49 @@
...
+ */
+function pmk_site_meets_php_requirements() {
+
+	return version_compare( phpversion(), pmk_minimum_php_requirement(), '>=' );
+}
+
```
Comment (faisal-alvi) [inline publisher-media-kit.php:44]: adding a comment here specifying the purpose of the below code would be nice to have.

**Review by faisal-alvi — COMMENTED** [review]
@bmarshall511 Thank you for the PR, LGTM. I tested it and saw the notice when the PHP version is below the minimum required. However, outlined a few minor tweaks below.

File: publisher-media-kit.php (hunk 1 above)
Comment (bmarshall511) [reply publisher-media-kit.php]: Updated

File: publisher-media-kit.php (hunk 2 above)
Comment (bmarshall511) [reply publisher-media-kit.php:68]: Updated

File: publisher-media-kit.php (hunk 3 above)
Comment (bmarshall511) [reply publisher-media-kit.php]: Updated

File: publisher-media-kit.php (hunk 4 above)
Comment (bmarshall511) [reply publisher-media-kit.php]: Updated

File: publisher-media-kit.php (hunk 5 above)
Comment (bmarshall511) [reply publisher-media-kit.php]: Updated

File: publisher-media-kit.php (hunk 6 above)
Comment (bmarshall511) [reply publisher-media-kit.php:44]: Updated

**Comment by bmarshall511** [comment]
> @bmarshall511 Thank you for the PR, LGTM. I tested it and saw the notice when the PHP version is below the minimum required. However, outlined a few minor tweaks below.

Thanks for taking a look @faisal-alvi! Updates made, ready for your review again.

**Review by faisal-alvi — DISMISSED** [review]

**Review by faisal-alvi — COMMENTED** [review]
@bmarshall511 The cypress tests are failing, I re ran the failed tests but they are still failing. I can see they passed in your first commit, but failed in the latest, can you please check it?

https://github.com/10up/publisher-media-kit/actions/runs/6352469169/job/17304966900#step:9:164

**Comment by faisal-alvi** [comment]
Note: The failed cypress tests are supposed to be fixed in https://github.com/10up/publisher-media-kit/pull/166

Let's wait until that is merged.

**Comment by ankitguptaindia** [comment]
Test Report: ✅ 
----

PR works as expected.

### When Plugin is already activated and PHP is downgraded later:


Screenshot 2023-10-30 at 8 07 12 PM


### When activating the plugin on PHP below 7.4: 

Screenshot 2023-10-30 at 8 08 49 PM

**Review by faisal-alvi — APPROVED** [review]
Manually updated the minimum required PHP version in the code to 8.2 to test in the 8.1 environment and it worked fine.

image

**Comment by faisal-alvi** [comment]
@jeffpaul can you please help to merge this one?
